import { mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';

const VERNACULAR_DIR = path.join(homedir(), 'vernacular');
const ENV_PATH = path.join(VERNACULAR_DIR, '.env');

/**
 * Write the station .env file to ~/vernacular/.env
 */
export function writeEnvFile(config) {
  mkdirSync(VERNACULAR_DIR, { recursive: true });

  const envContent = `# Vernacular iMessage Station Config
# Generated by @hedgeinc/vernacular-station on ${new Date().toISOString()}
# Do not edit manually — re-run 'vernacular-station connect' to update.

# Supabase
SUPABASE_URL=${config.supabaseUrl}
SUPABASE_SERVICE_KEY=${config.supabaseServiceKey}

# Notion
NOTION_TOKEN=${config.notionToken}
NOTION_DB=${config.notionDb}

# Vernacular API
VERNACULAR_API=${config.vernacularApi}

# Station Identity
STATION_NAME=${config.stationName}
STATION_PHONE=${config.stationPhone}
STATION_ID=${config.stationId}

# Behavior
AUTO_REPLY=${config.autoReply ?? 'true'}
POLL_INTERVAL_MS=${config.pollIntervalMs ?? 5000}
`;

  writeFileSync(ENV_PATH, envContent, 'utf-8');
  return ENV_PATH;
}

export function getEnvPath() {
  return ENV_PATH;
}

export function getVernacularDir() {
  return VERNACULAR_DIR;
}
